// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.productlocator.model;

import java.util.List;
import net.eyelock.productlocator.model.ContentBlock;
import net.eyelock.productlocator.model.ContentBlockDataOnDemand;
import net.eyelock.productlocator.model.ContentBlockIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContentBlockIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContentBlockIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContentBlockIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContentBlockIntegrationTest: @Transactional;
    
    @Autowired
    private ContentBlockDataOnDemand ContentBlockIntegrationTest.dod;
    
    @Test
    public void ContentBlockIntegrationTest.testCountContentBlocks() {
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to initialize correctly", dod.getRandomContentBlock());
        long count = ContentBlock.countContentBlocks();
        Assert.assertTrue("Counter for 'ContentBlock' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContentBlockIntegrationTest.testFindContentBlock() {
        ContentBlock obj = dod.getRandomContentBlock();
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to provide an identifier", id);
        obj = ContentBlock.findContentBlock(id);
        Assert.assertNotNull("Find method for 'ContentBlock' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ContentBlock' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContentBlockIntegrationTest.testFindAllContentBlocks() {
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to initialize correctly", dod.getRandomContentBlock());
        long count = ContentBlock.countContentBlocks();
        Assert.assertTrue("Too expensive to perform a find all test for 'ContentBlock', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ContentBlock> result = ContentBlock.findAllContentBlocks();
        Assert.assertNotNull("Find all method for 'ContentBlock' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ContentBlock' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContentBlockIntegrationTest.testFindContentBlockEntries() {
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to initialize correctly", dod.getRandomContentBlock());
        long count = ContentBlock.countContentBlocks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ContentBlock> result = ContentBlock.findContentBlockEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ContentBlock' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ContentBlock' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContentBlockIntegrationTest.testFlush() {
        ContentBlock obj = dod.getRandomContentBlock();
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to provide an identifier", id);
        obj = ContentBlock.findContentBlock(id);
        Assert.assertNotNull("Find method for 'ContentBlock' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContentBlock(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ContentBlock' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContentBlockIntegrationTest.testMergeUpdate() {
        ContentBlock obj = dod.getRandomContentBlock();
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to provide an identifier", id);
        obj = ContentBlock.findContentBlock(id);
        boolean modified =  dod.modifyContentBlock(obj);
        Integer currentVersion = obj.getVersion();
        ContentBlock merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ContentBlock' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContentBlockIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to initialize correctly", dod.getRandomContentBlock());
        ContentBlock obj = dod.getNewTransientContentBlock(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ContentBlock' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ContentBlock' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContentBlockIntegrationTest.testRemove() {
        ContentBlock obj = dod.getRandomContentBlock();
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContentBlock' failed to provide an identifier", id);
        obj = ContentBlock.findContentBlock(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ContentBlock' with identifier '" + id + "'", ContentBlock.findContentBlock(id));
    }
    
}
