// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.productlocator.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.productlocator.model.ArticleDataOnDemand;
import net.eyelock.productlocator.model.ContentBlock;
import net.eyelock.productlocator.model.ContentBlockDataOnDemand;
import net.eyelock.productlocator.model.ContentBlockType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ContentBlockDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContentBlockDataOnDemand: @Component;
    
    private Random ContentBlockDataOnDemand.rnd = new SecureRandom();
    
    private List<ContentBlock> ContentBlockDataOnDemand.data;
    
    @Autowired
    private ArticleDataOnDemand ContentBlockDataOnDemand.articleDataOnDemand;
    
    public ContentBlock ContentBlockDataOnDemand.getNewTransientContentBlock(int index) {
        ContentBlock obj = new ContentBlock();
        setContents(obj, index);
        setOrderedBy(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void ContentBlockDataOnDemand.setContents(ContentBlock obj, int index) {
        String contents = "contents_" + index;
        obj.setContents(contents);
    }
    
    public void ContentBlockDataOnDemand.setOrderedBy(ContentBlock obj, int index) {
        int orderedBy = 0;
        obj.setOrderedBy(orderedBy);
    }
    
    public void ContentBlockDataOnDemand.setType(ContentBlock obj, int index) {
        ContentBlockType type = ContentBlockType.class.getEnumConstants()[0];
        obj.setType(type);
    }
    
    public ContentBlock ContentBlockDataOnDemand.getSpecificContentBlock(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ContentBlock obj = data.get(index);
        Long id = obj.getId();
        return ContentBlock.findContentBlock(id);
    }
    
    public ContentBlock ContentBlockDataOnDemand.getRandomContentBlock() {
        init();
        ContentBlock obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ContentBlock.findContentBlock(id);
    }
    
    public boolean ContentBlockDataOnDemand.modifyContentBlock(ContentBlock obj) {
        return false;
    }
    
    public void ContentBlockDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ContentBlock.findContentBlockEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ContentBlock' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ContentBlock>();
        for (int i = 0; i < 10; i++) {
            ContentBlock obj = getNewTransientContentBlock(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
