/*
+---------+--------------+------+-----+---------+----------------+
| Field   | Type         | Null | Key | Default | Extra          |
+---------+--------------+------+-----+---------+----------------+
| id      | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| active  | bit(1)       | YES  |     | NULL    |                |
| code    | varchar(255) | NO   | UNI | NULL    |                |
| name    | varchar(255) | NO   |     | NULL    |                |
| version | int(11)      | YES  |     | NULL    |                |
+---------+--------------+------+-----+---------+----------------+
*/
START TRANSACTION;


INSERT INTO countries (active, code, name) VALUES
  (true, 'AF', 'Afghanistan')
, (true, 'AX', 'Aland Islands')
, (true, 'AL', 'Albania')
, (true, 'DZ', 'Algeria')
, (true, 'AS', 'American Samoa')
, (true, 'AD', 'Andorra')
, (true, 'AO', 'Angola')
, (true, 'AI', 'Anguilla')
, (true, 'AQ', 'Antarctica')
, (true, 'AG', 'Antigua and Barbuda')
, (true, 'AR', 'Argentina')
, (true, 'AM', 'Armenia')
, (true, 'AW', 'Aruba')
, (true, 'AU', 'Australia')
, (true, 'AT', 'Austria')
, (true, 'AZ', 'Azerbaijan')
, (true, 'BS', 'Bahamas')
, (true, 'BH', 'Bahrain')
, (true, 'BD', 'Bangladesh')
, (true, 'BB', 'Barbados')
, (true, 'BY', 'Belarus')
, (true, 'BE', 'Belgium')
, (true, 'BZ', 'Belize')
, (true, 'BJ', 'Benin')
, (true, 'BM', 'Bermuda')
, (true, 'BT', 'Bhutan')
, (true, 'BO', 'Bolivia,  Plurinational State of')
, (true, 'BQ', 'Bonaire,  Saint Eustatius and Saba')
, (true, 'BA', 'Bosnia and Herzegovina')
, (true, 'BW', 'Botswana')
, (true, 'BV', 'Bouvet Island')
, (true, 'BR', 'Brazil')
, (true, 'IO', 'British Indian Ocean Territory')
, (true, 'BN', 'Brunei Darussalam')
, (true, 'BG', 'Bulgaria')
, (true, 'BF', 'Burkina Faso')
, (true, 'BI', 'Burundi')
, (true, 'KH', 'Cambodia')
, (true, 'CM', 'Cameroon')
, (true, 'CA', 'Canada')
, (true, 'CV', 'Cape Verde')
, (true, 'KY', 'Cayman Islands')
, (true, 'CF', 'Central African Republic')
, (true, 'TD', 'Chad')
, (true, 'CL', 'Chile')
, (true, 'CN', 'China')
, (true, 'CX', 'Christmas Island')
, (true, 'CC', 'Cocos (Keeling) Islands')
, (true, 'CO', 'Colombia')
, (true, 'KM', 'Comoros')
, (true, 'CG', 'Congo')
, (true, 'CD', 'Congo,  The Democratic Republic of the')
, (true, 'CK', 'Cook Islands')
, (true, 'CR', 'Costa Rica')
, (true, 'CI', 'Cote D''ivoire')
, (true, 'HR', 'Croatia')
, (true, 'CU', 'Cuba')
, (true, 'CW', 'Curacao')
, (true, 'CY', 'Cyprus')
, (true, 'CZ', 'Czech Republic')
, (true, 'DK', 'Denmark')
, (true, 'DJ', 'Djibouti')
, (true, 'DM', 'Dominica')
, (true, 'DO', 'Dominican Republic')
, (true, 'EC', 'Ecuador')
, (true, 'EG', 'Egypt')
, (true, 'SV', 'El Salvador')
, (true, 'GQ', 'Equatorial Guinea')
, (true, 'ER', 'Eritrea')
, (true, 'EE', 'Estonia')
, (true, 'ET', 'Ethiopia')
, (true, 'FK', 'Falkland Islands (Malvinas)')
, (true, 'FO', 'Faroe Islands')
, (true, 'FJ', 'Fiji')
, (true, 'FI', 'Finland')
, (true, 'FR', 'France')
, (true, 'GF', 'French Guiana')
, (true, 'PF', 'French Polynesia')
, (true, 'TF', 'French Southern Territories')
, (true, 'GA', 'Gabon')
, (true, 'GM', 'Gambia')
, (true, 'GE', 'Georgia')
, (true, 'DE', 'Germany')
, (true, 'GH', 'Ghana')
, (true, 'GI', 'Gibraltar')
, (true, 'GR', 'Greece')
, (true, 'GL', 'Greenland')
, (true, 'GD', 'Grenada')
, (true, 'GP', 'Guadeloupe')
, (true, 'GU', 'Guam')
, (true, 'GT', 'Guatemala')
, (true, 'GG', 'Guernsey')
, (true, 'GN', 'Guinea')
, (true, 'GW', 'Guinea-Bissau')
, (true, 'GY', 'Guyana')
, (true, 'HT', 'Haiti')
, (true, 'HM', 'Heard Island and McDonald Islands')
, (true, 'VA', 'Holy See (Vatican City State)')
, (true, 'HN', 'Honduras')
, (true, 'HK', 'Hong Kong')
, (true, 'HU', 'Hungary')
, (true, 'IS', 'Iceland')
, (true, 'IN', 'India')
, (true, 'ID', 'Indonesia')
, (true, 'IR', 'Iran,  Islamic Republic of')
, (true, 'IQ', 'Iraq')
, (true, 'IE', 'Ireland')
, (true, 'IM', 'Isle of Man')
, (true, 'IL', 'Israel')
, (true, 'IT', 'Italy')
, (true, 'JM', 'Jamaica')
, (true, 'JP', 'Japan')
, (true, 'JE', 'Jersey')
, (true, 'JO', 'Jordan')
, (true, 'KZ', 'Kazakhstan')
, (true, 'KE', 'Kenya')
, (true, 'KI', 'Kiribati')
, (true, 'KP', 'Korea,  Democratic People''s Republic of')
, (true, 'KR', 'Korea,  Republic of')
, (true, 'KW', 'Kuwait')
, (true, 'KG', 'Kyrgyzstan')
, (true, 'LA', 'Lao People''s Democratic Republic')
, (true, 'LV', 'Latvia')
, (true, 'LB', 'Lebanon')
, (true, 'LS', 'Lesotho')
, (true, 'LR', 'Liberia')
, (true, 'LY', 'Libyan Arab Jamahiriya')
, (true, 'LI', 'Liechtenstein')
, (true, 'LT', 'Lithuania')
, (true, 'LU', 'Luxembourg')
, (true, 'MO', 'Macao')
, (true, 'MK', 'Macedonia,  The Former Yugoslav Republic of')
, (true, 'MG', 'Madagascar')
, (true, 'MW', 'Malawi')
, (true, 'MY', 'Malaysia')
, (true, 'MV', 'Maldives')
, (true, 'ML', 'Mali')
, (true, 'MT', 'Malta')
, (true, 'MH', 'Marshall Islands')
, (true, 'MQ', 'Martinique')
, (true, 'MR', 'Mauritania')
, (true, 'MU', 'Mauritius')
, (true, 'YT', 'Mayotte')
, (true, 'MX', 'Mexico')
, (true, 'FM', 'Micronesia,  Federated States of')
, (true, 'MD', 'Moldova,  Republic of')
, (true, 'MC', 'Monaco')
, (true, 'MN', 'Mongolia')
, (true, 'ME', 'Montenegro')
, (true, 'MS', 'Montserrat')
, (true, 'MA', 'Morocco')
, (true, 'MZ', 'Mozambique')
, (true, 'MM', 'Myanmar')
, (true, 'NA', 'Namibia')
, (true, 'NR', 'Nauru')
, (true, 'NP', 'Nepal')
, (true, 'NL', 'Netherlands')
, (true, 'NC', 'New Caledonia')
, (true, 'NZ', 'New Zealand')
, (true, 'NI', 'Nicaragua')
, (true, 'NE', 'Niger')
, (true, 'NG', 'Nigeria')
, (true, 'NU', 'Niue')
, (true, 'NF', 'Norfolk Island')
, (true, 'MP', 'Northern Mariana Islands')
, (true, 'NO', 'Norway')
, (true, 'OM', 'Oman')
, (true, 'PK', 'Pakistan')
, (true, 'PW', 'Palau')
, (true, 'PS', 'Palestinian Territory,  Occupied')
, (true, 'PA', 'Panama')
, (true, 'PG', 'Papua New Guinea')
, (true, 'PY', 'Paraguay')
, (true, 'PE', 'Peru')
, (true, 'PH', 'Philippines')
, (true, 'PN', 'Pitcairn')
, (true, 'PL', 'Poland')
, (true, 'PT', 'Portugal')
, (true, 'PR', 'Puerto Rico')
, (true, 'QA', 'Qatar')
, (true, 'RE', 'Reunion')
, (true, 'RO', 'Romania')
, (true, 'RU', 'Russian Federation')
, (true, 'RW', 'Rwanda')
, (true, 'BL', 'Saint Barthelemy')
, (true, 'SH', 'Saint Helena,  Ascension and Tristan Da Cunha')
, (true, 'KN', 'Saint Kitts and Nevis')
, (true, 'LC', 'Saint Lucia')
, (true, 'MF', 'Saint Martin (French Part)')
, (true, 'PM', 'Saint Pierre and Miquelon')
, (true, 'VC', 'Saint Vincent and the Grenadines')
, (true, 'WS', 'Samoa')
, (true, 'SM', 'San Marino')
, (true, 'ST', 'Sao Tome and Principe')
, (true, 'SA', 'Saudi Arabia')
, (true, 'SN', 'Senegal')
, (true, 'RS', 'Serbia')
, (true, 'SC', 'Seychelles')
, (true, 'SL', 'Sierra Leone')
, (true, 'SG', 'Singapore')
, (true, 'SX', 'Sint Maarten (Dutch Part)')
, (true, 'SK', 'Slovakia')
, (true, 'SI', 'Slovenia')
, (true, 'SB', 'Solomon Islands')
, (true, 'SO', 'Somalia')
, (true, 'ZA', 'South Africa')
, (true, 'GS', 'South Georgia and the South Sandwich Islands')
, (true, 'ES', 'Spain')
, (true, 'LK', 'Sri Lanka')
, (true, 'SD', 'Sudan')
, (true, 'SR', 'Suriname')
, (true, 'SJ', 'Svalbard and Jan Mayen')
, (true, 'SZ', 'Swaziland')
, (true, 'SE', 'Sweden')
, (true, 'CH', 'Switzerland')
, (true, 'SY', 'Syrian Arab Republic')
, (true, 'TW', 'Taiwan,  Province of China')
, (true, 'TJ', 'Tajikistan')
, (true, 'TZ', 'Tanzania,  United Republic of')
, (true, 'TH', 'Thailand')
, (true, 'TL', 'Timor-Leste')
, (true, 'TG', 'Togo')
, (true, 'TK', 'Tokelau')
, (true, 'TO', 'Tonga')
, (true, 'TT', 'Trinidad and Tobago')
, (true, 'TN', 'Tunisia')
, (true, 'TR', 'Turkey')
, (true, 'TM', 'Turkmenistan')
, (true, 'TC', 'Turks and Caicos Islands')
, (true, 'TV', 'Tuvalu')
, (true, 'UG', 'Uganda')
, (true, 'UA', 'Ukraine')
, (true, 'AE', 'United Arab Emirates')
, (true, 'GB', 'United Kingdom')
, (true, 'US', 'United States')
, (true, 'UM', 'United States Minor Outlying Islands')
, (true, 'UY', 'Uruguay')
, (true, 'UZ', 'Uzbekistan')
, (true, 'VU', 'Vanuatu')
, (true, 'VE', 'Venezuela,  Bolivarian Republic of')
, (true, 'VN', 'Viet Nam')
, (true, 'VG', 'Virgin Islands,  British')
, (true, 'VI', 'Virgin Islands,  U.S.')
, (true, 'WF', 'Wallis and Futuna')
, (true, 'EH', 'Western Sahara')
, (true, 'YE', 'Yemen')
, (true, 'ZM', 'Zambia')
, (true, 'ZW', 'Zimbabwe');


COMMIT;
