/*
+---------+--------------+------+-----+---------+----------------+
| Field   | Type         | Null | Key | Default | Extra          |
+---------+--------------+------+-----+---------+----------------+
| id      | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| active  | bit(1)       | YES  |     | NULL    |                |
| code    | varchar(255) | NO   | UNI | NULL    |                |
| name    | varchar(255) | NO   |     | NULL    |                |
| version | int(11)      | YES  |     | NULL    |                |
+---------+--------------+------+-----+---------+----------------+
*/
START TRANSACTION;


INSERT INTO countries (active, code, name, version) VALUES
  (true, 'AF', 'Afghanistan', 1)
, (true, 'AX', 'Aland Islands', 1)
, (true, 'AL', 'Albania', 1)
, (true, 'DZ', 'Algeria', 1)
, (true, 'AS', 'American Samoa', 1)
, (true, 'AD', 'Andorra', 1)
, (true, 'AO', 'Angola', 1)
, (true, 'AI', 'Anguilla', 1)
, (true, 'AQ', 'Antarctica', 1)
, (true, 'AG', 'Antigua and Barbuda', 1)
, (true, 'AR', 'Argentina', 1)
, (true, 'AM', 'Armenia', 1)
, (true, 'AW', 'Aruba', 1)
, (true, 'AU', 'Australia', 1)
, (true, 'AT', 'Austria', 1)
, (true, 'AZ', 'Azerbaijan', 1)
, (true, 'BS', 'Bahamas', 1)
, (true, 'BH', 'Bahrain', 1)
, (true, 'BD', 'Bangladesh', 1)
, (true, 'BB', 'Barbados', 1)
, (true, 'BY', 'Belarus', 1)
, (true, 'BE', 'Belgium', 1)
, (true, 'BZ', 'Belize', 1)
, (true, 'BJ', 'Benin', 1)
, (true, 'BM', 'Bermuda', 1)
, (true, 'BT', 'Bhutan', 1)
, (true, 'BO', 'Bolivia,  Plurinational State of', 1)
, (true, 'BQ', 'Bonaire,  Saint Eustatius and Saba', 1)
, (true, 'BA', 'Bosnia and Herzegovina', 1)
, (true, 'BW', 'Botswana', 1)
, (true, 'BV', 'Bouvet Island', 1)
, (true, 'BR', 'Brazil', 1)
, (true, 'IO', 'British Indian Ocean Territory', 1)
, (true, 'BN', 'Brunei Darussalam', 1)
, (true, 'BG', 'Bulgaria', 1)
, (true, 'BF', 'Burkina Faso', 1)
, (true, 'BI', 'Burundi', 1)
, (true, 'KH', 'Cambodia', 1)
, (true, 'CM', 'Cameroon', 1)
, (true, 'CA', 'Canada', 1)
, (true, 'CV', 'Cape Verde', 1)
, (true, 'KY', 'Cayman Islands', 1)
, (true, 'CF', 'Central African Republic', 1)
, (true, 'TD', 'Chad', 1)
, (true, 'CL', 'Chile', 1)
, (true, 'CN', 'China', 1)
, (true, 'CX', 'Christmas Island', 1)
, (true, 'CC', 'Cocos (Keeling) Islands', 1)
, (true, 'CO', 'Colombia', 1)
, (true, 'KM', 'Comoros', 1)
, (true, 'CG', 'Congo', 1)
, (true, 'CD', 'Congo,  The Democratic Republic of the', 1)
, (true, 'CK', 'Cook Islands', 1)
, (true, 'CR', 'Costa Rica', 1)
, (true, 'CI', 'Cote D''ivoire', 1)
, (true, 'HR', 'Croatia', 1)
, (true, 'CU', 'Cuba', 1)
, (true, 'CW', 'Curacao', 1)
, (true, 'CY', 'Cyprus', 1)
, (true, 'CZ', 'Czech Republic', 1)
, (true, 'DK', 'Denmark', 1)
, (true, 'DJ', 'Djibouti', 1)
, (true, 'DM', 'Dominica', 1)
, (true, 'DO', 'Dominican Republic', 1)
, (true, 'EC', 'Ecuador', 1)
, (true, 'EG', 'Egypt', 1)
, (true, 'SV', 'El Salvador', 1)
, (true, 'GQ', 'Equatorial Guinea', 1)
, (true, 'ER', 'Eritrea', 1)
, (true, 'EE', 'Estonia', 1)
, (true, 'ET', 'Ethiopia', 1)
, (true, 'FK', 'Falkland Islands (Malvinas)', 1)
, (true, 'FO', 'Faroe Islands', 1)
, (true, 'FJ', 'Fiji', 1)
, (true, 'FI', 'Finland', 1)
, (true, 'FR', 'France', 1)
, (true, 'GF', 'French Guiana', 1)
, (true, 'PF', 'French Polynesia', 1)
, (true, 'TF', 'French Southern Territories', 1)
, (true, 'GA', 'Gabon', 1)
, (true, 'GM', 'Gambia', 1)
, (true, 'GE', 'Georgia', 1)
, (true, 'DE', 'Germany', 1)
, (true, 'GH', 'Ghana', 1)
, (true, 'GI', 'Gibraltar', 1)
, (true, 'GR', 'Greece', 1)
, (true, 'GL', 'Greenland', 1)
, (true, 'GD', 'Grenada', 1)
, (true, 'GP', 'Guadeloupe', 1)
, (true, 'GU', 'Guam', 1)
, (true, 'GT', 'Guatemala', 1)
, (true, 'GG', 'Guernsey', 1)
, (true, 'GN', 'Guinea', 1)
, (true, 'GW', 'Guinea-Bissau', 1)
, (true, 'GY', 'Guyana', 1)
, (true, 'HT', 'Haiti', 1)
, (true, 'HM', 'Heard Island and McDonald Islands', 1)
, (true, 'VA', 'Holy See (Vatican City State)', 1)
, (true, 'HN', 'Honduras', 1)
, (true, 'HK', 'Hong Kong', 1)
, (true, 'HU', 'Hungary', 1)
, (true, 'IS', 'Iceland', 1)
, (true, 'IN', 'India', 1)
, (true, 'ID', 'Indonesia', 1)
, (true, 'IR', 'Iran,  Islamic Republic of', 1)
, (true, 'IQ', 'Iraq', 1)
, (true, 'IE', 'Ireland', 1)
, (true, 'IM', 'Isle of Man', 1)
, (true, 'IL', 'Israel', 1)
, (true, 'IT', 'Italy', 1)
, (true, 'JM', 'Jamaica', 1)
, (true, 'JP', 'Japan', 1)
, (true, 'JE', 'Jersey', 1)
, (true, 'JO', 'Jordan', 1)
, (true, 'KZ', 'Kazakhstan', 1)
, (true, 'KE', 'Kenya', 1)
, (true, 'KI', 'Kiribati', 1)
, (true, 'KP', 'Korea,  Democratic People''s Republic of', 1)
, (true, 'KR', 'Korea,  Republic of', 1)
, (true, 'KW', 'Kuwait', 1)
, (true, 'KG', 'Kyrgyzstan', 1)
, (true, 'LA', 'Lao People''s Democratic Republic', 1)
, (true, 'LV', 'Latvia', 1)
, (true, 'LB', 'Lebanon', 1)
, (true, 'LS', 'Lesotho', 1)
, (true, 'LR', 'Liberia', 1)
, (true, 'LY', 'Libyan Arab Jamahiriya', 1)
, (true, 'LI', 'Liechtenstein', 1)
, (true, 'LT', 'Lithuania', 1)
, (true, 'LU', 'Luxembourg', 1)
, (true, 'MO', 'Macao', 1)
, (true, 'MK', 'Macedonia,  The Former Yugoslav Republic of', 1)
, (true, 'MG', 'Madagascar', 1)
, (true, 'MW', 'Malawi', 1)
, (true, 'MY', 'Malaysia', 1)
, (true, 'MV', 'Maldives', 1)
, (true, 'ML', 'Mali', 1)
, (true, 'MT', 'Malta', 1)
, (true, 'MH', 'Marshall Islands', 1)
, (true, 'MQ', 'Martinique', 1)
, (true, 'MR', 'Mauritania', 1)
, (true, 'MU', 'Mauritius', 1)
, (true, 'YT', 'Mayotte', 1)
, (true, 'MX', 'Mexico', 1)
, (true, 'FM', 'Micronesia,  Federated States of', 1)
, (true, 'MD', 'Moldova,  Republic of', 1)
, (true, 'MC', 'Monaco', 1)
, (true, 'MN', 'Mongolia', 1)
, (true, 'ME', 'Montenegro', 1)
, (true, 'MS', 'Montserrat', 1)
, (true, 'MA', 'Morocco', 1)
, (true, 'MZ', 'Mozambique', 1)
, (true, 'MM', 'Myanmar', 1)
, (true, 'NA', 'Namibia', 1)
, (true, 'NR', 'Nauru', 1)
, (true, 'NP', 'Nepal', 1)
, (true, 'NL', 'Netherlands', 1)
, (true, 'NC', 'New Caledonia', 1)
, (true, 'NZ', 'New Zealand', 1)
, (true, 'NI', 'Nicaragua', 1)
, (true, 'NE', 'Niger', 1)
, (true, 'NG', 'Nigeria', 1)
, (true, 'NU', 'Niue', 1)
, (true, 'NF', 'Norfolk Island', 1)
, (true, 'MP', 'Northern Mariana Islands', 1)
, (true, 'NO', 'Norway', 1)
, (true, 'OM', 'Oman', 1)
, (true, 'PK', 'Pakistan', 1)
, (true, 'PW', 'Palau', 1)
, (true, 'PS', 'Palestinian Territory,  Occupied', 1)
, (true, 'PA', 'Panama', 1)
, (true, 'PG', 'Papua New Guinea', 1)
, (true, 'PY', 'Paraguay', 1)
, (true, 'PE', 'Peru', 1)
, (true, 'PH', 'Philippines', 1)
, (true, 'PN', 'Pitcairn', 1)
, (true, 'PL', 'Poland', 1)
, (true, 'PT', 'Portugal', 1)
, (true, 'PR', 'Puerto Rico', 1)
, (true, 'QA', 'Qatar', 1)
, (true, 'RE', 'Reunion', 1)
, (true, 'RO', 'Romania', 1)
, (true, 'RU', 'Russian Federation', 1)
, (true, 'RW', 'Rwanda', 1)
, (true, 'BL', 'Saint Barthelemy', 1)
, (true, 'SH', 'Saint Helena,  Ascension and Tristan Da Cunha', 1)
, (true, 'KN', 'Saint Kitts and Nevis', 1)
, (true, 'LC', 'Saint Lucia', 1)
, (true, 'MF', 'Saint Martin (French Part)', 1)
, (true, 'PM', 'Saint Pierre and Miquelon', 1)
, (true, 'VC', 'Saint Vincent and the Grenadines', 1)
, (true, 'WS', 'Samoa', 1)
, (true, 'SM', 'San Marino', 1)
, (true, 'ST', 'Sao Tome and Principe', 1)
, (true, 'SA', 'Saudi Arabia', 1)
, (true, 'SN', 'Senegal', 1)
, (true, 'RS', 'Serbia', 1)
, (true, 'SC', 'Seychelles', 1)
, (true, 'SL', 'Sierra Leone', 1)
, (true, 'SG', 'Singapore', 1)
, (true, 'SX', 'Sint Maarten (Dutch Part)', 1)
, (true, 'SK', 'Slovakia', 1)
, (true, 'SI', 'Slovenia', 1)
, (true, 'SB', 'Solomon Islands', 1)
, (true, 'SO', 'Somalia', 1)
, (true, 'ZA', 'South Africa', 1)
, (true, 'GS', 'South Georgia and the South Sandwich Islands', 1)
, (true, 'ES', 'Spain', 1)
, (true, 'LK', 'Sri Lanka', 1)
, (true, 'SD', 'Sudan', 1)
, (true, 'SR', 'Suriname', 1)
, (true, 'SJ', 'Svalbard and Jan Mayen', 1)
, (true, 'SZ', 'Swaziland', 1)
, (true, 'SE', 'Sweden', 1)
, (true, 'CH', 'Switzerland', 1)
, (true, 'SY', 'Syrian Arab Republic', 1)
, (true, 'TW', 'Taiwan,  Province of China', 1)
, (true, 'TJ', 'Tajikistan', 1)
, (true, 'TZ', 'Tanzania,  United Republic of', 1)
, (true, 'TH', 'Thailand', 1)
, (true, 'TL', 'Timor-Leste', 1)
, (true, 'TG', 'Togo', 1)
, (true, 'TK', 'Tokelau', 1)
, (true, 'TO', 'Tonga', 1)
, (true, 'TT', 'Trinidad and Tobago', 1)
, (true, 'TN', 'Tunisia', 1)
, (true, 'TR', 'Turkey', 1)
, (true, 'TM', 'Turkmenistan', 1)
, (true, 'TC', 'Turks and Caicos Islands', 1)
, (true, 'TV', 'Tuvalu', 1)
, (true, 'UG', 'Uganda', 1)
, (true, 'UA', 'Ukraine', 1)
, (true, 'AE', 'United Arab Emirates', 1)
, (true, 'GB', 'United Kingdom', 1)
, (true, 'US', 'United States', 1)
, (true, 'UM', 'United States Minor Outlying Islands', 1)
, (true, 'UY', 'Uruguay', 1)
, (true, 'UZ', 'Uzbekistan', 1)
, (true, 'VU', 'Vanuatu', 1)
, (true, 'VE', 'Venezuela,  Bolivarian Republic of', 1)
, (true, 'VN', 'Viet Nam', 1)
, (true, 'VG', 'Virgin Islands,  British', 1)
, (true, 'VI', 'Virgin Islands,  U.S.', 1)
, (true, 'WF', 'Wallis and Futuna', 1)
, (true, 'EH', 'Western Sahara', 1)
, (true, 'YE', 'Yemen', 1)
, (true, 'ZM', 'Zambia', 1)
, (true, 'ZW', 'Zimbabwe', 1);


COMMIT;
