// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.productlocator.model;

import net.eyelock.productlocator.model.Country;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Country_Roo_Configurable {
    
    declare @type: Country: @Configurable;
    
}
